version: '2'
services:
  ridesupport-getservices-ms:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    environment:
      - DATABASE_PASSWORD=root
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - ridesupport-getservices-db
    depends_on:
      - ridesupport-getservices-db
  ridesupport-getservices-db:
    image: mysql:5.7
    volumes:
      - /var/mysql-docker/ridesupport-getservices-ms:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "4408:3306"
