version: '2'
services:
  app:    
    build: .
    command: rails server -p 4000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    environment:
      - DATABASE_PASSWORD=root
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - /var/mysql-docker/RideSupport-Searching-ms:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3000:3000"
